/**
 * array for the tags available in the app
 */ 
export const tags = [
    'breakfast',
    'lunch',
    'dinner',
    'snack',
    'drink',
    'side',
    'main',
    'appetizer',
    'dessert',
    'beef',
    'pork',
    'chicken',
    'meat',
    'fish',
    'vegan',
    'vegetarian',
    'soup',
    'salad',
    'sweet',
    'savory',
    'spicy',
    'North American',
    'European',
    'English',
    'French',
    'Italian',
    'Asian',
    'Japanese',
    'Korean',
    'Filipino',
    'Vietnamese',
    'Chinese',
    'Middle Eastern',
] 